### ISSUE TITLE
Filter outputs garbage data when input is 16-bit depth

### ISSUE THREAD

**Issue by JohnstonJ** [Asd-g/AviSynth-vsCnr2#1]
This filter outputs garbage data when the input clip is 16-bit YUV444:

```
plugin_dir = "C:\VideoProject\Software\AviSynth-plugin\"

LoadPlugin(plugin_dir + "vsCnr2.dll")

ColorBars(pixel_type="YUV444P16")

vsCnr2()
```

I am viewing and testing this with 64-bit builds of AvsPmod v2.7.7.8 and AviSynth+ 3.7.3 (r4003, 3.7, x86_64), and vsCnr2 1.0.1 from the releases of this repo on Windows 10.

I open the output in the preview of AvsPmod.  Frame 0 looks ok, but if I scroll forward any number of frames, I get results like this:

![image](https://github.com/user-attachments/assets/626534ee-ebf0-4ea7-a091-4b0acfe4f8fb)

In a real world video in YUV444P16 format, I get garbage like this:

![image](https://github.com/user-attachments/assets/911f197c-c003-4dba-9a17-7d30fb70d7ad)

That was from an input frame like this:

![image](https://github.com/user-attachments/assets/1c147338-ba18-472d-9222-f7dc8661e1d6)

**Comment by Asd-g** [comment]
Try the new version `1.0.2`.
